name: Déploiement sous Nginx

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copier les fichiers via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "./public/*"
          target: "/var/www/app"

      - name: Provision Nginx (SSH)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            sudo apt-get update -y
            sudo apt-get install -y nginx
            sudo mkdir -p /var/www/app
            sudo chown -R $USER:$USER /var/www/app
            sudo tee /etc/nginx/sites-available/app > /dev/null <<'EOF'
            server {
              listen 80;
              server_name _;
              root /var/www/app;
              index index.html;
              location / { try_files $uri $uri/ =404; }
            }
            EOF
            sudo ln -sf /etc/nginx/sites-available/app /etc/nginx/sites-enabled/app
            sudo nginx -t
            sudo systemctl restart nginx
